name: image_processing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  camera: ^0.11.0+2
  camera_windows: ^0.2.5
  collection: ^1.18.0
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image: ^4.2.0
  image_picker: ^1.1.2
  uuid: ^4.5.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
